# Claude Code

Este proyecto sigue el estándar **Repos AI-ready** de Quind.
La fuente de verdad de reglas, contexto y convenciones es `AGENTS.md`.

@AGENTS.md

Los archivos en `.claude/` (skills, subagents, settings.json) son
extractos project-specific generados desde el TLM. No editar manualmente —
se regeneran con `agentic context --full`.

_Generated by DevCore F30 · project: QBCK-NEXT_
